namespace Payroll.Domain.Enums;

public enum EarningType
{
    Basic,
    HouseRentAllowance,
    ConveyanceAllowance,
    MedicalAllowance,
    SpecialAllowance,
    LeaveTravelAllowance,
    ChildrenEducationAllowance,
    ChildrenHostelAllowance,
    OverTime,
    OvertimeFlat,
    Bonus,
    PerformanceBonus,
    FixedBonus,
    CommissionOnSales,
    AdvanceSalary,
    Gratuity,
    ExGratia,
    NightShiftAllowance,
    CityCompensatoryAllowance,
    DearnesAllowance,
    UniformAllowance,
    ToolAllowance,
    WashingAllowance,
    MobileAllowance,
    InternetAllowance,
    FoodAllowance,
    BooksPeriodicals,
    HighAltitudeAllowance,
    BorderRemoteAllowance,
    // System-only: residual absorber. Cannot be created by tenants.
    FixedAllowance,
    ArrearsEarning,
    NotInList,
    Other,
}
