namespace Payroll.Domain.Enums;

public enum IndianState
{
    AndhraPradesh,
    ArunachalPradesh,
    Assam,
    Bihar,
    Chhattisgarh,
    Goa,
    Gujarat,
    Haryana,
    HimachalPradesh,
    Jharkhand,
    Karnataka,
    Kerala,
    MadhyaPradesh,
    Maharashtra,
    Manipur,
    Meghalaya,
    Mizoram,
    Nagaland,
    Odisha,
    Punjab,
    Rajasthan,
    Sikkim,
    TamilNadu,
    Telangana,
    Tripura,
    UttarPradesh,
    Uttarakhand,
    WestBengal,
    // Union Territories
    AndamanAndNicobar,
    Chandigarh,
    DadraAndNagarHaveliAndDamanAndDiu,
    Delhi,
    JammuAndKashmir,
    Ladakh,
    Lakshadweep,
    Puducherry,
}
