// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Payroll.Infrastructure.Persistence;

#nullable disable

namespace Payroll.Infrastructure.Migrations;

[DbContext(typeof(PayrollDbContext))]
[Migration("20260519174915_AddGratuityAmountToPayrunEmployee")]
partial class AddGratuityAmountToPayrunEmployee
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
